version: '3'
services:
  backend:
    build: .
    ports:
      - "8082:8080"
    container_name: seniors-green
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: