version: '3'
services:
  backend:
    build: .
    ports:
      - "8081:8080"
    container_name: seniors-blue
    depends_on:
      - redis
  redis:
      image: redis
      container_name: redis
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data

volumes:
  redis_data: