version: '3'
services:
  backend:
    build: .
    ports:
      - "8081:8080"
    container_name: seniors-blue
    environment:
      - REDIS_HOST = 13.209.247.218
      - REDIS_PORT = 6379
volumes:
  redis_data: