version: '3'
services:
  backend:
    build: .
    ports:
      - "8082:8080"
    container_name: seniors-green
    environment:
      - REDIS_HOST = 13.209.247.218
      - REDIS_PORT = 6379
    depends_on:
      - redis
volumes:
  redis_data: