version: '3'
services:
  backend:
    build: .
    ports:
      - "80:8080"
    container_name: seniors-blue
    environment:
      - REDIS_HOST = 43.203.78.235
      - REDIS_PORT = 6379
volumes:
  redis_data:
