version: '3'
services:
  backend:
    build: .
    ports:
      - "8082:8080"
    container_name: seniors-green
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
networks:
  default:
    driver: bridge